import { User, TimeSlot, Package, CustomPricingRule, Booking, Facility, LabSettings } from '@/types';

export const initialUsers: User[] = [
  {
    id: 'usr_admin',
    name: 'Lab Admin',
    email: 'admin@retrolab.com',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200',
    phone: '01700000000',
    institution: 'Retro Lab Headquarters',
    department: 'Lab Management',
    batch: '2025',
    role: 'ADMIN',
    createdAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'usr_pratik',
    name: 'Pratik Barua',
    email: 'pratik@diu.edu.bd',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&q=80&w=200',
    phone: '01712345678',
    institution: 'Daffodil International University',
    department: 'SWE',
    batch: '45th',
    role: 'USER',
    createdAt: '2025-08-10T10:30:00.000Z',
  },
  {
    id: 'usr_diu_robotics',
    name: 'DIU Robotics Club',
    email: 'robotics.club@diu.edu.bd',
    avatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&q=80&w=200',
    phone: '01898765432',
    institution: 'Daffodil International University',
    department: 'CSE / EEE',
    batch: 'Robotics Wing',
    role: 'USER',
    createdAt: '2025-08-12T14:20:00.000Z',
  },
  {
    id: 'usr_saif',
    name: 'Saif Ahmed',
    email: 'saif@diu.edu.bd',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200',
    phone: '01911223344',
    institution: 'Daffodil International University',
    department: 'EEE',
    batch: '42nd',
    role: 'USER',
    createdAt: '2025-08-15T09:00:00.000Z',
  },
  {
    id: 'usr_nafis',
    name: 'Nafis Imran',
    email: 'nafis@diu.edu.bd',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=200',
    phone: '01655443322',
    institution: 'Daffodil International University',
    department: 'CIS',
    batch: '38th',
    role: 'USER',
    createdAt: '2025-08-20T11:45:00.000Z',
  },
];

export const initialTimeSlots: TimeSlot[] = [
  { id: 'slot_1', dayOfWeek: 0, startTime: '10:00 AM', endTime: '12:00 PM', capacity: 10, isActive: true },
  { id: 'slot_2', dayOfWeek: 0, startTime: '12:00 PM', endTime: '02:00 PM', capacity: 10, isActive: true },
  { id: 'slot_3', dayOfWeek: 0, startTime: '02:00 PM', endTime: '04:00 PM', capacity: 10, isActive: true },
  { id: 'slot_4', dayOfWeek: 0, startTime: '04:00 PM', endTime: '06:00 PM', capacity: 10, isActive: true },
  { id: 'slot_5', dayOfWeek: 0, startTime: '06:00 PM', endTime: '08:00 PM', capacity: 10, isActive: true },
];

export const initialPackages: Package[] = [
  {
    id: 'pack_consultation',
    name: 'FREE CONSULTATION',
    minMembers: 1,
    maxMembers: 10,
    defaultDuration: 1,
    price: 0,
    isCustom: false,
    isActive: true,
    description: '100% Free • Expert Mentorship & Project Guidance',
  },
  {
    id: 'pack_solo',
    name: 'SOLO',
    minMembers: 1,
    maxMembers: 1,
    defaultDuration: 2,
    price: 140,
    isCustom: false,
    isActive: true,
    description: '1 Person • ৳140 / 2 hrs',
  },

  {
    id: 'pack_pair',
    name: 'PAIR',
    minMembers: 2,
    maxMembers: 2,
    defaultDuration: 2,
    price: 250,
    isCustom: false,
    isActive: true,
    description: '2 Persons • ৳250 / 2 hrs',
  },
  {
    id: 'pack_squad',
    name: 'SQUAD',
    minMembers: 3,
    maxMembers: 3,
    defaultDuration: 2,
    price: 330,
    isCustom: false,
    isActive: true,
    description: '3 Persons • ৳330 / 2 hrs',
  },
  {
    id: 'pack_team',
    name: 'TEAM',
    minMembers: 4,
    maxMembers: 4,
    defaultDuration: 2,
    price: 400,
    isCustom: false,
    isActive: true,
    description: '4 Persons • ৳400 / 2 hrs',
  },
  {
    id: 'pack_full_crew',
    name: 'FULL CREW',
    minMembers: 5,
    maxMembers: 5,
    defaultDuration: 2,
    price: 450,
    isCustom: false,
    isActive: true,
    description: '5 Persons • ৳450 / 2 hrs',
  },
  {
    id: 'pack_custom',
    name: 'CUSTOM PACK',
    minMembers: 1,
    maxMembers: 10,
    defaultDuration: 2,
    price: 140,
    isCustom: true,
    isActive: true,
    description: '1–10 Members • Custom duration • Live pricing',
  },
];

export const initialCustomPricingRules: CustomPricingRule[] = [
  // 1 member
  { id: 'cp_1_2', members: 1, duration: 2, price: 140, isActive: true },
  { id: 'cp_1_4', members: 1, duration: 4, price: 280, isActive: true },
  { id: 'cp_1_6', members: 1, duration: 6, price: 420, isActive: true },
  { id: 'cp_1_8', members: 1, duration: 8, price: 560, isActive: true },
  // 2 members
  { id: 'cp_2_2', members: 2, duration: 2, price: 250, isActive: true },
  { id: 'cp_2_4', members: 2, duration: 4, price: 500, isActive: true },
  { id: 'cp_2_6', members: 2, duration: 6, price: 750, isActive: true },
  { id: 'cp_2_8', members: 2, duration: 8, price: 1000, isActive: true },
  // 3 members
  { id: 'cp_3_2', members: 3, duration: 2, price: 330, isActive: true },
  { id: 'cp_3_4', members: 3, duration: 4, price: 660, isActive: true },
  { id: 'cp_3_6', members: 3, duration: 6, price: 990, isActive: true },
  { id: 'cp_3_8', members: 3, duration: 8, price: 1320, isActive: true },
  // 4 members
  { id: 'cp_4_2', members: 4, duration: 2, price: 400, isActive: true },
  { id: 'cp_4_4', members: 4, duration: 4, price: 800, isActive: true },
  { id: 'cp_4_6', members: 4, duration: 6, price: 1200, isActive: true },
  { id: 'cp_4_8', members: 4, duration: 8, price: 1600, isActive: true },
  // 5 members
  { id: 'cp_5_2', members: 5, duration: 2, price: 450, isActive: true },
  { id: 'cp_5_4', members: 5, duration: 4, price: 900, isActive: true },
  { id: 'cp_5_6', members: 5, duration: 6, price: 1350, isActive: true },
  { id: 'cp_5_8', members: 5, duration: 8, price: 1800, isActive: true },
  // 6 members
  { id: 'cp_6_2', members: 6, duration: 2, price: 500, isActive: true },
  { id: 'cp_6_4', members: 6, duration: 4, price: 900, isActive: true },
  { id: 'cp_6_6', members: 6, duration: 6, price: 1300, isActive: true },
  { id: 'cp_6_8', members: 6, duration: 8, price: 1700, isActive: true },
  // 7 members
  { id: 'cp_7_2', members: 7, duration: 2, price: 550, isActive: true },
  { id: 'cp_7_4', members: 7, duration: 4, price: 1000, isActive: true },
  { id: 'cp_7_6', members: 7, duration: 6, price: 1450, isActive: true },
  { id: 'cp_7_8', members: 7, duration: 8, price: 1900, isActive: true },
  // 8 members
  { id: 'cp_8_2', members: 8, duration: 2, price: 600, isActive: true },
  { id: 'cp_8_4', members: 8, duration: 4, price: 1100, isActive: true },
  { id: 'cp_8_6', members: 8, duration: 6, price: 1600, isActive: true },
  { id: 'cp_8_8', members: 8, duration: 8, price: 2100, isActive: true },
  // 9 members
  { id: 'cp_9_2', members: 9, duration: 2, price: 650, isActive: true },
  { id: 'cp_9_4', members: 9, duration: 4, price: 1200, isActive: true },
  { id: 'cp_9_6', members: 9, duration: 6, price: 1750, isActive: true },
  { id: 'cp_9_8', members: 9, duration: 8, price: 2300, isActive: true },
  // 10 members
  { id: 'cp_10_2', members: 10, duration: 2, price: 700, isActive: true },
  { id: 'cp_10_4', members: 10, duration: 4, price: 1300, isActive: true },
  { id: 'cp_10_6', members: 10, duration: 6, price: 1900, isActive: true },
  { id: 'cp_10_8', members: 10, duration: 8, price: 2500, isActive: true },
];

export const initialBookings: Booking[] = [
  {
    id: 'bk_1',
    bookingCode: 'RL20250830-1042',
    userId: 'usr_pratik',
    slotId: 'slot_1',
    bookingDate: '2025-08-30',
    startTime: '10:00 AM',
    endTime: '12:00 PM',
    duration: 2,
    packageId: 'pack_squad',
    packageName: 'SQUAD',
    members: 3,
    purpose: 'Embedded Systems & Sensor Integration Testing',
    totalPrice: 330,
    status: 'CONFIRMED',
    paymentStatus: 'PAID',
    customerName: 'Pratik Barua',
    customerPhone: '01712345678',
    institution: 'Daffodil International University',
    departmentBatch: 'SWE, 45th',
    createdAt: '2025-08-25T10:00:00.000Z',
  },
  {
    id: 'bk_2',
    bookingCode: 'RL20250830-1205',
    userId: 'usr_diu_robotics',
    slotId: 'slot_2',
    bookingDate: '2025-08-30',
    startTime: '12:00 PM',
    endTime: '02:00 PM',
    duration: 2,
    packageId: 'pack_full_crew',
    packageName: 'FULL CREW',
    members: 5,
    purpose: 'Autonomous Rover Chassis Assembly & PID Tuning',
    totalPrice: 450,
    status: 'CONFIRMED',
    paymentStatus: 'PAID',
    customerName: 'DIU Robotics Club',
    customerPhone: '01898765432',
    institution: 'Daffodil International University',
    departmentBatch: 'CSE / EEE',
    createdAt: '2025-08-26T14:15:00.000Z',
  },
  {
    id: 'bk_3',
    bookingCode: 'RL20250830-1422',
    userId: 'usr_saif',
    slotId: 'slot_3',
    bookingDate: '2025-08-30',
    startTime: '02:00 PM',
    endTime: '04:00 PM',
    duration: 2,
    packageId: 'pack_pair',
    packageName: 'PAIR',
    members: 2,
    purpose: 'PCB Soldering & Oscilloscope Signal Analysis',
    totalPrice: 250,
    status: 'PENDING',
    paymentStatus: 'UNPAID',
    customerName: 'Saif Ahmed',
    customerPhone: '01911223344',
    institution: 'Daffodil International University',
    departmentBatch: 'EEE, 42nd',
    createdAt: '2025-08-27T09:45:00.000Z',
  },
  {
    id: 'bk_4',
    bookingCode: 'RL20250830-1630',
    userId: 'usr_nafis',
    slotId: 'slot_4',
    bookingDate: '2025-08-30',
    startTime: '04:00 PM',
    endTime: '06:00 PM',
    duration: 2,
    packageId: 'pack_team',
    packageName: 'TEAM',
    members: 4,
    purpose: 'IoT Smart Agriculture Gateway Prototype',
    totalPrice: 400,
    status: 'CONFIRMED',
    paymentStatus: 'PAID',
    customerName: 'Nafis Imran',
    customerPhone: '01655443322',
    institution: 'Daffodil International University',
    departmentBatch: 'CIS, 38th',
    createdAt: '2025-08-28T16:20:00.000Z',
  },
];

export const initialFacilities: Facility[] = [
  {
    id: 'fac_1',
    name: 'Professional Workbench',
    description: 'ESD-safe dedicated electronics benches with high-intensity LED illumination and anti-static mats.',
    category: 'Workspace',
    imageUrl: '/images/workbench.webp',
    isActive: true,
    sortOrder: 1,
  },
  {
    id: 'fac_2',
    name: 'Electronics & Robotics Tools',
    description: 'Precision soldering stations, hot-air rework guns, digital multimeter, wire strippers, and crimping kits.',
    category: 'Tools',
    imageUrl: '/images/tools.webp',
    isActive: true,
    sortOrder: 2,
  },
  {
    id: 'fac_3',
    name: 'Oscilloscope & Test Equipment',
    description: '100MHz Dual-Channel Digital Storage Oscilloscopes, DC regulated bench power supplies, and logic analyzers.',
    category: 'Testing',
    imageUrl: '/images/oscilloscope.webp',
    isActive: true,
    sortOrder: 3,
  },
  {
    id: 'fac_4',
    name: 'Mentoring & Technical Guidance',
    description: 'On-site senior robotics engineers to guide circuit troubleshooting, code debugging, and hardware selection.',
    category: 'Mentorship',
    imageUrl: '/images/mentoring.webp',
    isActive: true,
    sortOrder: 4,
  },
  {
    id: 'fac_5',
    name: 'High-Speed Wi-Fi & Workstations',
    description: '100 Mbps fiber internet for datasheet research, schematic download, firmware compilation, and GitHub sync.',
    category: 'Infrastructure',
    imageUrl: '/images/wifi.webp',
    isActive: true,
    sortOrder: 5,
  },
];

export const initialLabSettings: LabSettings = {
  labName: 'RETRO LAB',
  tagline: 'from idea >> to prototype',
  maxMembers: 10,
  defaultSlotDuration: 2,
  openingTime: '10:00 AM',
  closingTime: '08:00 PM',
  advanceBookingDays: 30,
  cancellationPolicy: 'Free cancellation up to 4 hours before the booked time slot.',
  contactEmail: 'contact@retrolab.com',
  contactPhone: '+880 1700-000000',
  address: 'Daffodil Smart City, Ashulia, Dhaka, Bangladesh',
};
